apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myriad-web.fullname" . }}
  labels:
    {{- include "myriad-web.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "myriad-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "myriad-web.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "myriad-web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NEXT_PUBLIC_APP_NAME
              value: {{ .Values.config.appName }}
            - name: NEXTAUTH_URL
              value: {{ .Values.config.nextAuthURL }}
            - name: SECRET
              value: {{ .Values.config.nextSecret }}
            - name: NEXT_PUBLIC_API_URL
              value: {{ .Values.config.apiURL }}
            - name: NEXT_PUBLIC_MYRIAD_WS_RPC
              value: {{ .Values.config.rpcWSURL }}
            - name: NEXT_PUBLIC_FIREBASE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "myriad-web.firebaseSecretName" . }}
                  key: projectId
            - name: NEXT_PUBLIC_FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "myriad-web.firebaseSecretName" . }}
                  key: apiKey
            - name: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "myriad-web.firebaseSecretName" . }}
                  key: messagingSenderId
            - name: NEXT_PUBLIC_FIREBASE_APP_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "myriad-web.firebaseSecretName" . }}
                  key: appId
            {{- if .Values.config.sentry.dns }}
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "myriad-web.sentrySecretName" . }}
                  key: dns
            {{- end }}
            - name: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "myriad-web.cloudinarySecretName" . }}
                  key: cloudName
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "myriad-web.cloudinarySecretName" . }}
                  key: apiKey
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "myriad-web.cloudinarySecretName" . }}
                  key: secret
            - name: NEXT_PUBLIC_FACEBOOK_APP_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "myriad-web.facebookSecretName" . }}
                  key: appId
            - name: TWITTER_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "myriad-web.twitterSecretName" . }}
                  key: bearerToken
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          startupProbe:
            httpGet:
              path: /api/healthcheck
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /api/healthcheck
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /api/healthcheck
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
